bookHandler/urls.py
# urls for the bookHandler app
from . import views
from django.urls import path

app_name='bookHandler'
urlpatterns=[
    path('', views.book_index, name='index'),
    path('detail/<int:book_id>/', views.abstract_detailed_view, name='detail_abstract'),
    path('detail_actual/<uuid:book_id>/', views.actualBook_detailed_view, name='detail_actual'),
    path('author/<int:author_id>/', views.author_detailed_view, name='detail_author'),
    path('new_book', views.add_book_view, name='add_book'),
    path('user_profile',views.profile_view, name='user_profile'),
    path('new_transaction/<uuid:book_id>', views.new_borrowing_request, name='new_transaction'),
    path('reply_transaction/<uuid:transaction_id>',views.reply_request, name='reply_transaction'),
    path('edit_transaction/<uuid:transaction_id>', views.edit_transaction, name='edit_transaction'),
    path('view_conversation/<uuid:transaction_id>', views.view_conversation, name='view_conversation'),
    path('my_books', views.my_books_view, name='user_books'),
    path('my_requests', views.my_requests_view, name='user_requests'),
]

nisekobookclub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from bookHandler import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookhandler/', include('bookHandler.urls')),
    path('', views.book_index, name='home' ),
    # Authentification views
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
    path('register/', views.register, name='register' )
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookHandler/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
from django.utils import timezone
from django.conf import settings # for the settings.AUTH_USER_MODEL
from django.urls import reverse

# Create your models here.

class User(AbstractUser):
    AREA_LOCATIONS = (
        ('nh', 'Higashiyama (Niseko-cho)'),
        ('nt', 'Niseko-cho town'),
        ('nk', 'Kondo Niseko-cho'),
        ('kh', 'Hirafu (Kutchan-cho)'),
        ('kk', 'Kabayama (Kutchan-cho)'),
        ('kt', 'Kutchan town center'),
        ('oo', 'Others'),
    )
    location = models.TextField(max_length=2, choices=AREA_LOCATIONS, default='nt')
    
    def get_absolute_url(self):
        return reverse('bookHandler:user_profile')

class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, db_index=True)
    text = models.TextField(max_length=500, blank=True)
    read = models.BooleanField(default=False, db_index=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"
        ordering = ['-timestamp']
    
    def __str__(self):
        return self.text 

class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, db_index=True, related_name='messages_written')
    destination = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, db_index=True, related_name='messages_received')
    transaction = models.ForeignKey('Transaction', on_delete=models.SET_NULL, null=True, db_index=True, related_name='messages')
    text = models.TextField(max_length=500, blank=True)
    read = models.BooleanField(default=False, db_index=True)
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)

    class Meta:
        verbose_name = "Message"
        verbose_name_plural = "Messages"
        ordering = ['-timestamp']
    
    def __str__(self):
        return '%s to %s - %s' % (self.author, self.destination, self.text)
   
    def save(self, *args, **kwargs):
        """ Updates the created date value """
        if not self.id:
            self.timestamp = timezone.now()
        return super(Message,self).save(args,kwargs)


class Genre(models.Model):
    """ Model representing a book genre """
    name = models.CharField(max_length=200, help_text='Enter a book genre(e.g. crime, historical fiction, ...')
    # To Do: a foreignkey to self in order to point to the various translated fields. 
    # Then a method to translate into a language would return the proper translation, or the original value if not translated yet
    # (And ideally do an admin method in order to see what needs to be translated)

    def __str__(self):
        return self.name

class AbstractBook(models.Model):
    """ Model represents a generic book, not an actual physical book """
    title = models.CharField(max_length=200)
    author = models.ManyToManyField('Author')
    summary = models.TextField(max_length=1000, help_text='Enter a quick description for the model')
    isbn = models.CharField('ISBN', max_length=13, help_text='International code (10 or 13 digits)')
    genre = models.ManyToManyField(Genre, help_text='Select one or many genres for this book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('bookHandler:detail_abstract', args=[self.id])


    @staticmethod
    def get_or_create(title, author_list_string, book_summary=''):
        """
        get_or_create will look for the corresponding book and create it, if not found.
        title: String with the book title
        author_list_string: A list of strings containing Author names, preferably with LAST NAME first (e.g. Einstein Albert)
        book_summary: An (optional) string with the summary
        """
        author_list = []
        for author_string in author_list_string:
            new_author = Author.get_or_create(author_string)
            author_list.append(new_author)

        query_filters = models.Q()
        if title != '':
            query_filters &= models.Q(title=title)
        results = AbstractBook.objects.filter(query_filters)
        for author in author_list:
            # We supposed that the string is well constructed with LAST
            query_filters = models.Q(author__last_name=author.last_name) & models.Q(author__first_name=author.first_name)
            results = results.filter(query_filters) # We chain the filter instead of the Qs because of the ManyToMany relationship

        if len(results) == 0:
            new_book = AbstractBook(title=title, summary=book_summary, isbn='')
            new_book.save() # The author 'ManyToMany' needs the object to be created in order to allow an author to be added
            for author in author_list:
                new_book.author.add(author)
            new_book.save()
            return new_book
        else:
            return results[0]

class ActualBook(models.Model):
    """ Model will represent an actual physical book, owned by someone and on the lend/borrow market """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this actual book' )
    abstract_book = models.ForeignKey(AbstractBook, on_delete=models.CASCADE, related_name='instances')
    created_date = models.DateField(editable=False, default=timezone.now)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, default=1, related_name='book_inventory')
    AVAILABLE = 'a'
    UNAVAILABLE = 'u'
    OUT_FOR_RENT = 'o'
    BOOK_STATUS = (
        (AVAILABLE, 'Available'),
        (UNAVAILABLE, 'Unavailable'), # Not borrowed but lost, damaged or owner wants to remove from the market
        (OUT_FOR_RENT, 'Borrowed'),
    )
    status = models.CharField(max_length=1, choices=BOOK_STATUS, default='a')

    class Meta:
        ordering = ['-created_date']

    def get_absolute_url(self):
        return reverse('bookHandler:detail_actual', args=[self.id])

    def __str__(self):
        return '%s - owned by %s (%s)' % (self.abstract_book.title,self.owner.username, self.id)

class Author(models.Model):
    """ Model represents the list of authors """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField(max_length=500, default='', null=True, verbose_name='biography')
    class Meta:
        ordering = ['last_name', 'first_name']
    
    def get_absolute_url(self):
        return reverse('bookHandler:detail_author', args=[self.id])
    
    def __str__(self):
        return '%s %s' % (self.last_name, self.first_name)

    @staticmethod
    def get_or_create(author):
        #First, assume last name first 
        last_name = author.split()[0].title()
        if len(author)>len(last_name):
            first_name = author[len(last_name)+1:].title()
        else:
            first_name = ''
        queryset_and = Author.objects.filter(first_name__iexact=first_name) & Author.objects.filter(last_name__iexact=last_name)
        if len(queryset_and) == 0:
            # Author not found - trying to reverse first and last name
            last_name_2 = author.split()[-1].title()
            if len(author)>len(last_name_2):
                first_name_2 = author[:len(author)-len(last_name_2)].title().strip()
            else:
                first_name_2 = ''
            queryset_and = Author.objects.filter(first_name__iexact=first_name_2) & Author.objects.filter(last_name__iexact=last_name_2)            
            if len(queryset_and) == 0:
                # Giving up - have to create a new author
                # Using the initial variables (last_name, first_name) as they correspond to the LAST NAME FIRST convention (e.g. Einstein Albert)
                new_author = Author(last_name=last_name, first_name=first_name)
                new_author.save()
                return new_author
            else:
                return queryset_and[0]
        else:
            return queryset_and[0]
        
class Transaction(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for the transaction')
    book = models.ForeignKey(ActualBook, on_delete=models.CASCADE,related_name='transactions')
    lender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='lend_requests' )
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='borrow_requests')
    created_date = models.DateField(default=timezone.now, editable=False)
    modified_timestamp = models.DateTimeField(default=timezone.now, editable=False)
    lend_date = models.DateField(default=timezone.now)
    return_date = models.DateField(default=timezone.now)

    INITIAL_REQUEST = 'i'
    APPROVED_REQUEST = 'a'
    REJECTED_REQUEST = 'k'
    BOOK_LENT = 'l'
    BOOK_RETURNED = 'r'
    EXTENSION = 'e'
    BOOK_LOST = 'z'
    ACTIVE_TRANSACTION = [INITIAL_REQUEST, APPROVED_REQUEST, BOOK_LENT, EXTENSION]

    TRANSACTION_STATUS = (
        (INITIAL_REQUEST, 'Initial Request'),
        (APPROVED_REQUEST, 'Request Approved'),
        (REJECTED_REQUEST, 'Request Rejected'),
        (BOOK_LENT, 'Book lent'),
        (BOOK_RETURNED, 'Book returned'),
        (EXTENSION, 'Extension'),
        (BOOK_LOST, 'Book Lost')
    )
    transaction_state = models.CharField(max_length=1, choices=TRANSACTION_STATUS, default='i')
    
    class Meta:
        ordering=['-lend_date']

    def __str__(self):
        return '"%s" on %s btw %s and %s' % (self.book.abstract_book.title, self.lend_date, self.book.owner, self.borrower)
    
    def save(self, *args, **kwargs):
        """ Updates the created date value """

bookHandler/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from bookHandler.models import User, Transaction

class UserBookForm(forms.Form):
    """ this class will be used to edit an actual book in a user-convenient way.
        On the back-end it will create (if necessary) one instance of ActualBook and one instance of AbstractBook, Author etc...
        """
    
    isbn = forms.CharField(max_length=20, required=False)
    title = forms.CharField(max_length=100, required=True,help_text='Enter the book title')
    author = forms.CharField(max_length=50, required=True, help_text='Enter authors separated by commas, last name first')
    genre = forms.CharField(max_length=100, required=False)
    summary = forms.CharField(required=False, widget=forms.Textarea)

class RegisterForm(UserCreationForm):
    """ Extends the basic User Creation Form with supplementary fields """
    first_name = forms.CharField(max_length=30,required=False)
    last_name = forms.CharField(max_length=30,required=False)
    email = forms.EmailField(max_length=254,help_text='Required. Please input a valid e-mail address')

    class Meta:
        model = User
        fields = ('username','first_name','last_name','email', 'password1','password2', 'location')

class TransactionReplyForm(forms.Form):
    """ Form used by a book owner to reply to incoming requests. (reply with yes or no) """
    REPLY_CHOICES = [('Yes','Accept to lend the book'), ('No','Refuse to lend the book')]
    owner_reply = forms.ChoiceField(choices=REPLY_CHOICES, widget=forms.RadioSelect())
    lend_date = forms.DateField()
    return_date = forms.DateField()
    transaction_id = forms.UUIDField(widget=forms.HiddenInput)
    message = forms.CharField(max_length=500, required=False, widget=forms.Textarea(attrs={'class':'form-control'}) )

    class Meta:
        fields = ('owner_reply', 'lend_date', 'return_date', 'message')

class EditTransactionForm(forms.ModelForm):

    new_message = forms.CharField(max_length=500, required=False,help_text='Enter an optional answer', widget=forms.Textarea)

    class Meta:
        model = Transaction
        fields = ['lend_date', 'return_date', 'transaction_state', 'new_message']
        
    def __init__(self, *args, **kwargs):
        super(EditTransactionForm,self).__init__(*args, **kwargs)
        self.fields['lend_date'].widget = forms.DateInput(attrs={'class':'form-control datepicker'},format='%m/%d/%Y')
        self.fields['return_date'].widget = forms.DateInput(attrs={'class':'form-control datepicker'},format='%m/%d/%Y')
        for field in iter(self.fields):
            if self.fields[field].widget.__class__.__name__ in ('AdminTextInputWidget' , 'Textarea' ,'TextInput', 'NumberInput' , 'AdminURLFieldWidget', 'Select'):
                self.fields[field].widget.attrs.update({ 'class': 'form-control' })

class NewMessageForm(forms.Form):

    message_text = forms.CharField(max_length=500, required=False, widget=forms.Textarea(attrs={'class':'form-control'}) )

bookHandler/templates/bookHandler/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <link rel="stylesheet" href="{% static 'recipeViewer/bootstrap.min.css' %}" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title> {% block title %} Niseko Book Club {% endblock %}</title>


</head>
<body>
    <!-- Displaying messages if needed -->
    {%  if messages  %}
        {% for message in messages %}
            {% if message.tags == "error" %}
                <div class="alert alert-danger"> {{ message }} </div>
            {% else %}
                <div class="alert alert-{{message.tags}}"> {{ message }} </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <!-- Main Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
        <a class="navbar-brand">Niseko Book Club</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item pr-3">
                    <a class="nav-link" href="{% url 'bookHandler:index' %}">Home</a>
                </li>
                <li class="nav-item pr-3">
                    <a class="nav-link" href="">News</a>
                </li>
                <li class="nav-item pr-3">
                    <a class="nav-link">Search</a>
                </li>
                <!-- Buttons related with authentification -->
                {% if user.is_authenticated  %}
                    <li class="nav-item pr-3">
                        <a class="nav-link" href="{% url 'bookHandler:user_books' %}">My Books</a>
                    </li>
                    <li class="nav-item pr-3">
                        <a class="nav-link" href="{% url 'bookHandler:user_requests' %}">My Requests</a>
                    </li>
                    
                    <li class="nav-item pr-3">
                        <a class="nav-link" href="{% url 'bookHandler:user_profile' %}"> {{user.username}} Profile</a>
                    </li>
                    
                   <li class="nav-item pr-3">
                        <a class="nav-link" href="{%url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item pr-3">
                        <a class="nav-link" href="{%url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item pr-3">
                        <a class="nav-link" href="{%url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>

        </div>

    </nav>

    {% block body %}


    {% endblock %}

<footer class="bd-footer text-muted bg-light my-4">
    
    <p class="small"> Made with <a href="https://www.djangoproject.com">Django</a> and <a href="https://getbootstrap.com/">Bootstrap</a>. Pictures from <a href="https://unsplash.com/">Unsplash</a></p>
</footer>

{% block javascript %}
{% endblock %}

</body>


</html>

bookHandler/templates/bookHandler/books-index.html
{% extends 'bookHandler/base.html' %}

{% load static %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Welcome to Niseko Book Club!</h1>
        <figure class="figure">
            <img src="{% static 'old-library-thin.jpg' %}" class="figure-img img-fluid rounded">
            <figcaption class="figure=caption text-right">
                Photo by <a href="https://unsplash.com/@annahunko?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Anna Hunko</a> on <a href="https://unsplash.com/s/photos/library?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a>
            </figcaption>
        </figure>
    </div>
</div>
<div class="row bg-light justify-content-center"> Current List of Books</div>

<div class="container mb-4 justify-content-start" id="mainBookList">
{% for book, author in book_list_with_author %}
    <div class="row">
        <div class="col"> 
            <a href="{% url  'bookHandler:detail_abstract' book.id %}"> {{ book.title }} </a> 
            ( {{ author }} )
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}

bookHandler/templates/bookHandler/detailed-abstract-book.html
{% extends 'bookHandler/base.html' %}

{% block body %}

<div class="container">
    <div class="row bg-light">
        <h2> {{ book.title }} </h2>
        
    </div>
    <div class="row">
        <div class="col offset-1">
            <h3> {% for author in author_list %} 
                <a href="{% url 'bookHandler:detail_author' author.id %}">{{ author }} </a>
                {% if not forloop.last %} , {% endif %} {% endfor %} </h3>
            <ul>
                <li> ISBN = {{ book.isbn }}</li>
                <li> {% for genre_label in genre_list %} {{ genre_label }} {% endfor %} </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-1"> Book summary:</div>
        <div class="col">
            {{ book.summary }}
        </div>
    </div>

    <div class="row">
        List of existing books for this title:
    </div>

    <table class="table align-middle">
        <thead class="thead-light"> <tr><th> id </th> <th> Created Date </th> <th> Status </th> <th> Owner </th> <th>Status</th>  </tr></thead>
        {% for actualBook in actual_list %}
            <tr> <td class="align-middle"> <a href="{% url 'bookHandler:detail_actual' actualBook.id %}">{{actualBook.id | truncatechars:10}} </a></td> 
                <td class="align-middle"> {{ actualBook.created_date | timesince }} </td> 
                <td class="align-middle"> {{ actualBook.get_status_display }} </td> 
                <td class="align-middle"> {{ actualBook.owner }} </td> 
            <td class="align-middle">
                {% if actualBook.status == actualBook.AVAILABLE and actualBook.owner != user %}
                <form method="POST" action="{% url 'bookHandler:new_transaction' actualBook.id %}" class="form-inline"> 
                    {% csrf_token %} <button type="submit" class="btn btn-primary">Request</button> 
                </form> {% else %} <a class="btn btn-secondary btn-disabled">(Not available)</a> {% endif %}
            </td>
            </tr>
        {% endfor %}
    </table>


</div>


{% endblock %}

bookHandler/templates/bookHandler/detailed-actual-book.html
{% extends 'bookHandler/base.html' %}

{% block body %}

<div class="container">
    <div class="row bg-light">
        <h2> {{ abstract_book.title }} </h2>
        
    </div>
    <div class="row">
        {% for author in abstract_book.author.all %}
        <h3> {{ author }} {% if not forloop.last %} , {% endif %} </h3>
        {% endfor %}
    </div>

    <div class="row">
        Book created on {{actual_book.created_date}}. <br>
        Book Owner: {{actual_book.owner}} living around {{actual_book.owner.get_location_display}} <br>
        Status: {{actual_book.get_status_display}}
    </div>

    <div class="row">
        List of past transactions for this title:
    </div>

    <table class="table">
        <tr><th> Borrower </th> <th> Borrowed Date </th> <th> Returned Date </th> <th> Rating </th>  </tr>
        {% for transaction in transactions_list %}
            <tr> <td> {{ transaction.borrower }} </td> <td> {{ transaction.lend_date }} </td> <td> {{ transaction.return_date }} </td> <td>  </td> </tr>
        {% endfor %}
    </table>
</div>


{% endblock %}

bookHandler/templates/bookHandler/my-book-list.html
{% extends 'bookHandler/base.html' %}

{% block title %} Niseko Book Club : My Books {% endblock %}

{% block body %}

<div class="row justify-content-center mb-4">
    <div class="col-10">
        <h3> My Books</h3>
        {% for actual_book, current_transaction in book_list %}
            <div class="row border rounded border-secondary mb-1">
                <div class="col-sm-auto"><h5><a href="{% url 'bookHandler:detail_actual' actual_book.id %}">{{ actual_book.abstract_book.title }}  </a> </h5> </div>
                <div class="col-sm-4 col-md-auto"><em>({% for author in actual_book.abstract_book.author.all %} {{ author.last_name }} {{ author.first_name }} {% if not forloop.last %} , {% endif %}  {% endfor %}) </em></div>
                <div class="col-6 col-sm-4 col-md-auto"> <em>Placeholder for physical state</em> </div>
                <div class="col-md-6"> <span class="badge {% if not current_transaction %} badge-success {% else %}  badge-primary {% endif %}"> {{ actual_book.get_status_display }}</span> {% if current_transaction %} {{ current_transaction.borrower }} until {{current_transaction.return_date }} {% endif %} </div>
                <div class="col-12"><!-- Line feed to get the buttons all on one line--></div>
                <div class="col-md-8 offset-sm-2 text-center">
                    {% if current_transaction %} 
                        <a href="{% url 'bookHandler:edit_transaction' current_transaction.id %}" class="btn btn-primary">Edit Transaction</a> 
                        <a href="{% url 'bookHandler:view_conversation' current_transaction.id %}" class="btn btn-primary">View Conversation</a> 
                    {% endif %}
                </div>
            </div>
        {% endfor %}

    </div>
</div>
<div class="row ">
    <div class="col-sm-4 offset-sm-1">
        <a href="{%url 'bookHandler:add_book' %}" class="btn btn-primary">Add Book</a>
    </div>
</div>

{% endblock %}

bookHandler/templates/bookHandler/my-requests.html
{% extends 'bookHandler/base.html' %}

{% block title %} Niseko Book Club : My Requests {% endblock %}

{% block body %}

<div class="row justify-content-center mb-4">
    <div class="col-10">
        <h5>Book Borrowed request and status </h5>
            <p><small>List of books that you would like to read and requested</small></p>

            {% for transaction in transaction_list %}
                <div class="row border rounded secondary-border mb-1 p-2">
                    <div class="col-sm-auto"> <h5>{{ transaction.book.abstract_book.title }}</h5></div>
                    <div class="col-sm-4 col-md-auto"> <em> ({% for author in transaction.book.abstract_book.author.all %} {{ author.last_name }} {{ author.first_name }} {% if not forloop.last %} , {% endif %}  {% endfor %}) </em> </div>
                    <div class="col-sm-4 col-md-auto"> owner: {{transaction.lender }} - until {{ transaction.return_date }} </div>
                    <div class="col"> <span class="badge badge-success">{{transaction.get_transaction_state_display}} </span> </div>
                    <div class="col"> <a href="{% url 'bookHandler:view_conversation' transaction.id %}" class="btn btn-primary"> View Conversation </a>  </div>

                </div>
            {% endfor %}

    </div>
</div>

{% endblock %}

bookHandler/templates/bookHandler/reply-transaction.html
{% extends 'bookHandler/base.html' %}

{% block body %}

<h3> Edit transaction </h3>

<ul class="list-group">
    <li class="list-group-item">  {{ transaction.borrower }} requested to borrow the book below:</li>
    <li class="list-group-item"> <h3>Book Title: {{ transaction.book.abstract_book.title  }} </h3> </li>
    <li class="list-group-item"> <h6>Book author(s): {% for author in transaction.book.abstract_book.author.all %} {{ author }} {% if not forloop.last %} , {% endif %} {% endfor %} </em></h6></li>
    <li class="list-group-item"> Book owner: {{ transaction.lender }} </li>
    <li class="list-group-item"> Request created on: {{ transaction.created_date }} </li>
</ul>

<div class="row justify-content-center">
    <div class="col-4">
        <form method="POST" action="{% url 'bookHandler:reply_transaction' transaction.id %}">
            {% csrf_token %}
            <ul class="list-group">
                {{ form.as_ul }}
            </ul>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        
    </div>    
</div>

{% endblock %}